name: GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allow mannually trigger 
  workflow_dispatch:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      
      - name: Build Cookbook
        run: make cookbook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book


# References:
# * [mdBook Official Docs](https://rust-lang.github.io/mdBook/)
# * [mdBook Automated Deployment](https://github.com/rust-lang/mdBook/wiki/Automated-Deployment)
# * [peaceiris Github Pages Action](https://github.com/peaceiris/actions-gh-pages)